
plugins:
  - jekyll-seo-tag

# Jekyll defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

url: https://usemy.name

# Theme settings / site variables
title: "Use My Name!"
description: A comprehensive resource dedicated to promoting the importance of using names correctly and respectfully.
copyright: "Copyright ©️ 2024 Use My Name! Project"
google_analytics: G-SD5G0LEHCX
show_downloads: false

twitter:
  username: "@usemy_dot_name"

github:
  is_project_page: false
