
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank

# Jekyll defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: /assets/images/name-tag.png

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - ".idea"

liquid:
  error_mode: strict

sass:
  verbose: true

url: https://usemy.name

# Purely to remove the file extension from links
permalink: /:categories/:year/:month/:day/:title

# Theme settings / site variables
title: "Use My Name!"
description: A comprehensive resource dedicated to promoting the importance of using names correctly and respectfully.
copyright: "Copyright ©️ 2024,2026 Use My Name! Project"
# google_analytics: G-SD5G0LEHCX
google_tag_manager: GT-TQVFT5T

callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow

twitter:
  username: "@usemy_dot_name"
