
plugins:
  - jekyll-seo-tag

# Jekyll defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      image: /assets/images/name-tag.png

url: https://usemy.name

# Theme settings / site variables
title: "Use My Name!"
description: A comprehensive resource dedicated to promoting the importance of using names correctly and respectfully.
copyright: "Copyright ©️ 2024 Use My Name! Project"
google_analytics: G-SD5G0LEHCX

twitter:
  username: "@usemy_dot_name"
