
plugins:
  - jekyll-remote-theme

url: https://usemy.name/
remote_theme: pages-themes/cayman@v0.2.0

# Theme settings / site variables
title: "Use My Name!"
description: A comprehensive resource dedicated to promoting the importance of using names correctly and respectfully.
google_analytics: G-SD5G0LEHCX
show_downloads: false

github:
  is_project_page: false
